site_name: Winterbloom Big Honking Button User Guide
copyright: "© 2020 Winterbloom, licensed under Creative Commons CC BY-SA 4.0"
repo_url: "https://github.com/theacodes/Winterbloom-Big-Honking-Button"
edit_uri: edit/master/user_guide/docs
theme:
  name: null
  custom_dir: 'theme/'
markdown_extensions:
  - admonition
  - def_list
  - attr_list
  - toc:
      permalink: "#"
      toc_depth: 2
  - pymdownx.highlight:
      use_pygments: True
  - pymdownx.superfences
nav:
  - "User Guide": index.md
  - "Kit Build Instructions": build.md